name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Dependencies
      working-directory: ./core
      run: pip install -r requirements.txt
    
    - name: Run Migrations
      working-directory: ./core
      run: python manage.py migrate
    
    - name: Run Flake8
      working-directory: ./core
      run: flake8
    
    - name: Run Tests
      working-directory: ./core
      run: pytest .
