name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Django
      working-directory: ./core  
      run: python manage.py runserver
    - name: Run Tests
      working-directory: ./core 
      run: flake8 && pytest
